/* Generated by ./src/xlat/gen.sh from ./src/xlat/rtnl_ifla_br_boolopt_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat rtnl_ifla_br_boolopt_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data rtnl_ifla_br_boolopt_flags_xdata[] = {
 XLAT_PAIR(1ULL<<BR_BOOLOPT_NO_LL_LEARN, "1<<BR_BOOLOPT_NO_LL_LEARN"),
 #define XLAT_VAL_0 ((unsigned) (1ULL<<BR_BOOLOPT_NO_LL_LEARN))
 #define XLAT_STR_0 "1<<BR_BOOLOPT_NO_LL_LEARN"
 XLAT_PAIR(1ULL<<BR_BOOLOPT_MCAST_VLAN_SNOOPING, "1<<BR_BOOLOPT_MCAST_VLAN_SNOOPING"),
 #define XLAT_VAL_1 ((unsigned) (1ULL<<BR_BOOLOPT_MCAST_VLAN_SNOOPING))
 #define XLAT_STR_1 "1<<BR_BOOLOPT_MCAST_VLAN_SNOOPING"
};
static
const struct xlat rtnl_ifla_br_boolopt_flags[1] = { {
 .data = rtnl_ifla_br_boolopt_flags_xdata,
 .size = ARRAY_SIZE(rtnl_ifla_br_boolopt_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
